### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by nieziqi123** [acheong08/ChatGPT-Proxy-V1#6]
go build .\main.go
internal\api\openai.go:19:13: pattern config.json: no matching files found

**Comment by coolmian** [comment]
Please see README
```
CONFIG IS HIDDEN AND NOT SHARED
```

**Comment by cjb1234567** [comment]
> Please see README
> 
> ```
> CONFIG IS HIDDEN AND NOT SHARED
> ```

then how to get config.json?

**Comment by uniqueni** [comment]
> > Please see README
> > ```
> > CONFIG IS HIDDEN AND NOT SHARED
> > ```
> 
> then how to get config.json?

自己加一个

**Comment by cjb1234567** [comment]
> 

在主目录加一个空文件？

**Comment by jianhuihi** [comment]
> Please see README
> 
> ```
> CONFIG IS HIDDEN AND NOT SHARED
> ```

自己托管server端，不需要改config.conf ?

**Comment by newdots** [comment]
> > > Please see README
> > > ```
> > > CONFIG IS HIDDEN AND NOT SHARED
> > > ```
> > 
> > 
> > then how to get config.json?
> 
> 自己加一个
我还是没跑起来，大佬您跑起来了吗

**Comment by cjb1234567** [comment]
没有使用说明，跑不起来，可能给大佬用的，得看代码慢慢研究，go看不太懂。

**Comment by coolmian** [comment]
Start the binary directly on the ubuntu22.10 system without compiling the source code.

**Comment by kof4467** [comment]
This project is an HTTP proxy that forwards client requests to the server at the config.endpoint and then returns the server's response to the client. While there are many solutions online that can do this, the most important part is the hidden config.json. I guess config.endpoint is the key to bypassing Cloudflare.

**Comment by zwmcoder** [comment]
So, where is the endpoint,  it is another proxy again?  it looks like : ChatGPT -> ChatGPT-Proxy-V1 -> xxxxx-proxy -> openai now。

**Comment by acheong08** [comment]
Not open source to prevent it from being taken down. V2 was taken down after I open sourced the config
